#configuracion de base de datos
spring:
  datasource:
    url: jdbc:mysql://nature-life.cnhfconl9pyh.us-west-1.rds.amazonaws.com/nature_life
    username: admin
    password: Blacklist2019-
    tomcat.max-wait: 20000
    tomcat.max-active: 50
    tomcat.max-idle: 20
    tomcat.min-idle: 15

  jpa:
    show-sql: true
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: com.nature.life.config.FraudMySQLDialect
    properties:
      hibernate:
        auto_quote_keyword: true
        physical_naming_strategy: com.nature.life.config.PhysicalNamingStrategyImpl
        dialect: com.nature.life.config.FraudMySQLDialect
        enable_lazy_load_no_trans: true
        id:
          new_generator_mappings: false
        hbm2ddl:
          auto: update

#################################
server.port: 8080